"""What changed in the client pack between builds, and when.

`mc mrpack` rebuilds the pack from whatever is in `client-install/mods/` right
now. That folder is the only record of what a player is being asked to install,
and it has no memory: once a jar is swapped the previous build is unknowable,
so "what did I change last week" cannot be answered after the fact. This module
is that memory -- the mod set as of the last release, and the diff that produced
each one.

Two files come out of it, for the two readers. `pack-history.json` is the state:
the current set, and every release as a diff against the one before it. It is
what the next build compares against, so it is the file that must not be edited
by hand. `CHANGELOG.md` is the same history rendered for a person, newest
first, and is regenerated from the JSON every time.

A mod that is merely updated arrives here as a removal and an addition, because
the version is in the filename and nothing else distinguishes the two. Pairing
them back up is what `identity` does: strip the version-ish tokens off a jar
name and two builds of the same mod land on the same key. The pairing is only
believed when it is unambiguous -- one jar leaving and one arriving under that
key -- so a mod that genuinely split into two files is reported as what it
looks like rather than guessed at.
"""

from __future__ import annotations

import re
from collections.abc import Iterable, Sequence
from datetime import datetime
from pathlib import Path

from pydantic import BaseModel, ConfigDict, ValidationError

BANNER = "<!-- Generated by `mc mrpack` -- do not edit by hand. -->"

# Jar names separate their parts with these; `.` is deliberately not one of
# them, so that `26.2.x` stays a single token and is recognised as a version.
SPLIT = re.compile(r"[-_+ ]+")

# Tokens that say which build of a mod this is rather than which mod it is.
# Only ever dropped after the first token, so `fabric-api` keeps its name.
NOISE = frozenset(
    {"fabric", "forge", "neoforge", "quilt", "mc", "minecraft", "client", "server"}
)


class ChangelogError(RuntimeError):
    """The recorded history could not be read."""


def identity(filename: str) -> str:
    """The mod a jar is a build *of*.

    Everything after the first token that carries a digit or names a loader is
    dropped, which is what makes two builds of one mod compare equal. The first
    token is always kept: some mods have a digit in their actual name (`c2me`),
    and dropping it would leave nothing to key on.
    """
    stem = filename[:-4] if filename.lower().endswith(".jar") else filename
    tokens = [token for token in SPLIT.split(stem) if token]
    if not tokens:
        return filename.lower()
    kept = [tokens[0]] + [
        token
        for token in tokens[1:]
        if not any(char.isdigit() for char in token) and token.lower() not in NOISE
    ]
    return "-".join(kept).lower()


def _by_identity(names: Iterable[str]) -> dict[str, list[str]]:
    grouped: dict[str, list[str]] = {}
    for name in names:
        grouped.setdefault(identity(name), []).append(name)
    return grouped


class ModUpdate(BaseModel):
    """One mod that stayed in the pack under a new build."""

    model_config = ConfigDict(frozen=True)

    mod: str  # the identity both filenames share
    before: str
    after: str


class Release(BaseModel):
    """One build of the pack, as the difference from the build before it."""

    model_config = ConfigDict(frozen=True)

    version: str
    built_at: datetime
    added: tuple[str, ...] = ()
    removed: tuple[str, ...] = ()
    updated: tuple[ModUpdate, ...] = ()
    # True for the build that started the history. Its `added` is the whole
    # pack, which is a fact about the record beginning rather than about
    # anything having been added, and reads as nonsense presented as a diff.
    initial: bool = False

    @property
    def changed(self) -> bool:
        return bool(self.added or self.removed or self.updated)

    @property
    def summary(self) -> str:
        if self.initial:
            return f"first recorded build -- {len(self.added)} mods"
        if not self.changed:
            return "no mod changes"
        counts = (
            (len(self.added), "added"),
            (len(self.removed), "removed"),
            (len(self.updated), "updated"),
        )
        return ", ".join(f"{count} {label}" for count, label in counts if count)


class Changelog(BaseModel):
    """Every release, newest first, plus the set the next build diffs against.

    `mods` is stored rather than replayed from the diffs: a history that has to
    be summed to be read is a history that a single hand-edit makes silently
    wrong about the present.
    """

    model_config = ConfigDict(frozen=True)

    mods: tuple[str, ...] = ()
    releases: tuple[Release, ...] = ()

    @classmethod
    def load(cls, path: Path) -> Changelog:
        """The history so far. Empty when there is none, which is not an error.

        A file that exists and does not parse *is* one. Treating it as empty
        would record the entire pack as newly added and overwrite the only copy
        of what was there before.
        """
        if not path.exists():
            return cls()
        try:
            return cls.model_validate_json(path.read_text())
        except (OSError, ValidationError, ValueError) as exc:
            raise ChangelogError(f"{path.name} is not a readable pack history: {exc}") from exc

    @property
    def latest(self) -> Release | None:
        return self.releases[0] if self.releases else None

    def release(self, mods: Sequence[str], version: str, when: datetime | None = None) -> Release:
        """What a build of `mods` would be recorded as. Records nothing."""
        before, after = set(self.mods), set(mods)
        if not self.releases and not self.mods:
            return Release(
                version=version,
                built_at=when or datetime.now(),
                added=tuple(sorted(after)),
                initial=True,
            )

        gone = _by_identity(before - after)
        arrived = _by_identity(after - before)
        updated = [
            ModUpdate(mod=key, before=olds[0], after=arrived[key][0])
            for key, olds in gone.items()
            # One out and one in under the same name is an update. Anything
            # else is reported as what it is rather than paired on a guess.
            if len(olds) == 1 and len(arrived.get(key, ())) == 1
        ]
        paired = {change.before for change in updated} | {change.after for change in updated}
        return Release(
            version=version,
            built_at=when or datetime.now(),
            added=tuple(sorted(after - before - paired)),
            removed=tuple(sorted(before - after - paired)),
            updated=tuple(sorted(updated, key=lambda change: change.mod)),
        )

    def record(
        self, mods: Sequence[str], version: str, when: datetime | None = None
    ) -> tuple[Changelog, Release]:
        """This history plus that build, and the release it was recorded as.

        A rebuild that changed nothing is not a release: it leaves the history
        exactly as it was, so the file only ever grows when the pack did.
        """
        entry = self.release(mods, version, when)
        if not entry.changed:
            return self, entry
        return Changelog(mods=tuple(sorted(mods)), releases=(entry, *self.releases)), entry

    # ------------------------------------------------------------- writing

    def save(self, path: Path) -> bool:
        """Write the history. True when the file actually changed."""
        return _write(path, self.model_dump_json(indent=2) + "\n")

    def export(self, path: Path) -> bool:
        """Write the human-readable changelog. True when it actually changed."""
        return _write(path, self.render())

    def render(self) -> str:
        lines = [
            "# Client pack changelog",
            "",
            BANNER,
            "",
            "Every build of the client pack that changed the mod set, newest first.",
            "`mc mrpack` appends to this; a rebuild that changes nothing is not a release.",
            "",
        ]
        if not self.releases:
            lines += ["Nothing recorded yet.", ""]
            return "\n".join(lines)

        lines += [f"Currently **{len(self.mods)}** mods.", ""]
        for entry in self.releases:
            lines += self._section(entry)
        return "\n".join(lines)

    @staticmethod
    def _section(entry: Release) -> list[str]:
        lines = [
            f"## {entry.version} -- {entry.built_at:%Y-%m-%d %H:%M}",
            "",
            entry.summary,
            "",
        ]
        if entry.initial:
            lines += [f"- `{name}`" for name in entry.added] + [""]
            return lines
        for label, names in (("Added", entry.added), ("Removed", entry.removed)):
            if names:
                lines += [f"**{label}**", ""]
                lines += [f"- `{name}`" for name in names]
                lines += [""]
        if entry.updated:
            lines += ["**Updated**", ""]
            lines += [
                f"- `{change.mod}` -- `{change.before}` to `{change.after}`"
                for change in entry.updated
            ]
            lines += [""]
        return lines


def _write(path: Path, content: str) -> bool:
    """Write only when the bytes differ, so an unchanged rebuild is a no-op."""
    if path.exists() and path.read_text() == content:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)
    return True
