"""Stand-ins for the two mod folders, for the version control they cannot enter.

Redistributing other people's jars is a licence violation almost everywhere, so
a server that is also a repository cannot commit `mods/`. What goes in their
place is this manifest: filename, project, version, size and the CDN url for
that exact build, which is enough to rebuild either folder from a clone.

It is generated from a live scan rather than kept by hand. The hand-maintained
table it replaced had drifted to 110 of 163 jars -- silently, because nothing
could tell. Nothing here is timestamped, so regenerating an unchanged folder
produces a byte-identical file and an empty diff; drift shows up as a real one.
"""

from __future__ import annotations

from pathlib import Path

from pydantic import BaseModel, ConfigDict

from .mods import ModReport, ModScan
from .units import human_bytes

BANNER = "<!-- Generated by `mc mods manifest` -- do not edit by hand. -->"

SERVER_INTRO = """These are the mods the server runs. A client does **not** need them; see
[`client-install/`](../client-install/) for what players install.

Download each file below into `mods/`, then run `mc mods check` to confirm the
set matches. Versions are exact: a different build of the same mod can change
worldgen or break the save."""

CLIENT_INTRO = """These are the mods a player needs to connect. The easy path is the Modrinth
pack -- [`../modrinth.index.json`](../modrinth.index.json) is its manifest, and
`mc mrpack` builds an importable `.mrpack` from it. Installing by hand instead
means downloading every file below into `.minecraft/mods/`.

Read [`../README.txt`](../README.txt) first; it covers the Fabric loader
version, memory, and the shaderpacks."""


class Manifest(BaseModel):
    """One mod folder, rendered as the markdown file that stands in for it."""

    model_config = ConfigDict(frozen=True)

    title: str
    folder: str
    intro: str
    loader: str
    scan: ModScan

    @classmethod
    def for_server(cls, scan: ModScan, loader: str) -> Manifest:
        return cls(
            title="Server mods",
            folder="mods/",
            intro=SERVER_INTRO,
            loader=loader,
            scan=scan,
        )

    @classmethod
    def for_client(cls, scan: ModScan, loader: str) -> Manifest:
        return cls(
            title="Client mods",
            folder="client-install/mods/",
            intro=CLIENT_INTRO,
            loader=loader,
            scan=scan,
        )

    @property
    def hosted(self) -> list[ModReport]:
        """Mods with a resolvable download -- the rebuildable part of the set."""
        return [report for report in self.scan.reports if report.mod.url]

    @property
    def unhosted(self) -> list[ModReport]:
        """Mods Modrinth cannot serve. Named anyway: a manifest that quietly
        dropped them would describe a set that does not run."""
        return [report for report in self.scan.reports if not report.mod.url]

    @property
    def total_size(self) -> int:
        return sum(report.mod.size for report in self.scan.reports)

    def render(self) -> str:
        count = len(self.scan.reports)
        lines = [
            f"# {self.title}",
            "",
            BANNER,
            "",
            f"Jars are **not** committed (licensing). This is the manifest for `{self.folder}`.",
            "",
            f"Minecraft **{self.scan.minecraft}** · Fabric Loader **{self.loader}** · "
            f"**{count}** mods · {human_bytes(self.total_size)}",
            "",
            self.intro,
            "",
            "| Mod | Version | File | Size |",
            "|---|---|---|---|",
        ]
        lines += [self._row(report) for report in self.hosted]

        if self.unhosted:
            lines += [
                "",
                f"## Not on Modrinth ({len(self.unhosted)})",
                "",
                "No CDN link exists for these, so they cannot be scripted. Ask the admin,",
                "or find them on the author's own page.",
                "",
                "| File | Size |",
                "|---|---|",
            ]
            lines += [
                f"| `{report.mod.filename}` | {human_bytes(report.mod.size)} |"
                for report in self.unhosted
            ]

        lines.append("")
        return "\n".join(lines)

    @staticmethod
    def _row(report: ModReport) -> str:
        mod = report.mod
        name = f"[{mod.label}]({mod.page})" if mod.page else mod.label
        return (
            f"| {name} | `{mod.version_number or '?'}` | "
            f"[`{mod.filename}`]({mod.url}) | {human_bytes(mod.size)} |"
        )

    def write(self, path: Path) -> bool:
        """Write the manifest. True when the file actually changed.

        Reporting the change is what lets `--check` run the same code path as a
        write, so the check can never disagree with what a write would produce.
        """
        rendered = self.render()
        if path.exists() and path.read_text() == rendered:
            return False
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(rendered)
        return True

    def matches(self, path: Path) -> bool:
        """True when the file on disk is already what a write would produce."""
        try:
            return path.read_text() == self.render()
        except OSError:
            return False
